[package]
name = "fdk-mqa-node-namer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
avro-rs = "0.13.0"
futures = "0.3.21"
oxigraph = "0.3.2"
rdkafka = "0.28.0"
schema_registry_converter = { version = "2.1.0", features = ["avro", "blocking"] }
serde = "1.0.137"
serde_derive = "1.0.137"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
