[package]
name = "fdk-mqa-assmentator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.1.0"
avro-rs = "0.13.0"
futures = "0.3.26"
lazy_static = "1.4.0"
oxigraph = "0.3.2"
prometheus = "0.13.1"
rdkafka = "0.28.0"
schema_registry_converter = { version = "2.1.0", features = ["avro", "futures", "rustls_tls"], default-features=false }
serde = "1.0.137"
serde_derive = "1.0.137"
sha2 = "0.10.2"
thiserror = "1.0.31"
tokio = { version = "1.18.2", features = ["full"] }
tracing = "0.1.36"
tracing-subscriber =  { version = "0.3.11", features = ["json"] }
uuid = "1.1.2"
