[package]
name = "fdk-mqa-assmentator"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4.4.0"
apache-avro = "0.16.0"
futures = "0.3.29"
lazy_static = "1.4.0"
oxigraph = "0.3.20"
prometheus = "0.13.3"
rdkafka = "0.36.0"
schema_registry_converter = { version = "4.0.0", features = ["avro", "futures", "rustls_tls"], default-features=false }
serde = "1.0.192"
serde_derive = "1.0.192"
sha2 = "0.10.8"
thiserror = "1.0.50"
tokio = { version = "1.39.2", features = ["full"] }
tracing = "0.1.40"
tracing-subscriber =  { version = "0.3.17", features = ["json", "env-filter", "tracing-log"] }
uuid = "1.5.0"
