---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - service-fdk-mqa-assmentator.yaml
  - deployment-fdk-mqa-assmentator.yaml

images:
  - name: fdk-mqa-assmentator
    newName: ghcr.io/informasjonsforvaltning/fdk-mqa-assmentator
    newTag: $(GIT_COMMIT_SHA)
